name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install black ruff pytest pytest-cov

    - name: Lint with ruff
      run: |
        ruff check src/ tests/
      continue-on-error: true

    - name: Format check with black
      run: |
        black --check src/ tests/
      continue-on-error: true

    - name: Run tests
      run: |
        pytest tests/ -v --cov=src --cov-report=term-missing

    - name: Validate Week11 structure
      run: |
        python -m src.cli.validate_week_and_kit 11
